### ISSUE TITLE
names are incorrectly globally lower-cased

### ISSUE THREAD

**Issue by sevko** [pelias/quattroshapes-pipeline#14]
As per [this pelias/pelias issue](https://github.com/pelias/pelias/issues/26#issuecomment-71030260), the Quattroshapes province name "West-Vlanderen" appears as "West-vlanderen" in search results. Tracked it down to the [`src.mapper.capitalize()`](https://github.com/pelias/quattroshapes-pipeline/blob/master/src/mapper.js#L9,#L20) function. Why are we globally lower-casing strings?

**Comment by hkrishna** [comment]
https://github.com/pelias/suggester-pipeline/blob/master/lib/inputGenerator.js#L6-L14
https://github.com/pelias/quattroshapes-pipeline/blob/master/src/mapper.js#L9,%23L20

**Comment by missinglink** [comment]
It looks like I didn't foresee hyphenated names when this code was originally written. If I recall correctly this code was originally intended to normalize admin names (some were all lowercase).

Is it sufficient to add a hyphen to the regex or do we need to totally rethink a i18n capitalization strategy?

**Comment by sevko** [comment]
Both. We'll obviously want to figure out robust text-correction in the future, but that's probably not a priority at the moment.
